### ISSUE TITLE
Data with no label

### ISSUE THREAD

**Issue by AriaeiMehdi** [ByungKwanLee/Causal-Unsupervised-Segmentation#11]
Hi,
I would like to know if it is possible to train CAUSE without labels available?

thanks 
Mehdi.

**Comment by AkankshaP0102** [comment]
Hey did you get any luck in using  the model without labels. Please can you let me know the results.
Thank you in Advance.

**Comment by AriaeiMehdi** [comment]
> Hey @AriaeiMehdi did you get any luck in using the model without labels. Please can you let me know the results. Thank you in Advance.

Hi, In my case I had some labels available so I didn't get to train without labels. As far as I understand, you can train the mediator script (train_mediator.py)with no labels. here is the part of the code that just loads the images and trains the network without labels:
https://github.com/ByungKwanLee/Causal-Unsupervised-Segmentation/blob/45cf51029e2580f53bff618bf48598b974cc8482/train_mediator.py#L30-L32

but the author used labels in train_front_door.py and fine_tuning.py(tr and mlp) script to calculate linear loss.
you may need to ignore linear loss in these scripts to train without labels.
