### ISSUE TITLE
Computation required for training and training time

### ISSUE THREAD

**Issue by smeenapadnekar** [ByungKwanLee/Causal-Unsupervised-Segmentation#8]
Computation required for training and training time

**Comment by ByungKwanLee** [comment]
This contents are included in the paper. You can see them

**Comment by ByungKwanLee** [comment]
Oh! I didn't update the arxiv paper for time complexity

Under experiment environment (CPU: Intel(R) Xeon(R) Gold 6230R, GPU: RTX 3090 × 4EA, and RAM: 256GB), we take step1 with 10 min, 30 min, 45 min, 1 hour, and 10 min to perform modularity maximization on Cityscapes, COCO-Stuff, COCO-81, COCO-171, and Pascal-VOC 2012.

For Step 2, 30-45 min, 2-3 hour, 3-4 hour, 4-5 hour, and 30-45 min are each taken on Cityscapes, COCO-Stuff, COCO-81, COCO-171, and Pascal VOC 2012 with total two or three epochs.

Note that, Distributed Data Parallel (DDP) with 16 batches per GPU and Mixed Precision (float32-float16) are together used to technically more reduce computation in the environment setting.
